In [2]:
# Подключаем необходимые для анализа библиотеки

from IPython.display import display
import pandas as pd
import scipy as sp
import matplotlib.pyplot as plt
from scipy.stats import norm
import math as ms
import numpy as np

In [3]:
def normal_plot(df, array):
    voters = array
    x = voters
    
    source = {"Index": ["ind"]*len(x), "voters" : x} # Индексируем сырой массив из кол-ва избирателей представленной выборки

    df = pd.DataFrame(source)

    df_mean = np.mean(df["voters"])
    print('\nСреднее значение данной выборки = ', df_mean)
    
    df_std = np.std(df["voters"])
    print('\nНормальное отклонение  данной выборки = ', df_std)
    
    # Расчёт Probability Density Function/Функция плотности вероятности (array, mu, sigma)
    # Применяется на сортированный массив
    pdf = norm.pdf(df["voters"].sort_values(), df_mean, df_std)
    
    plt.plot(df["voters"].sort_values(), pdf)
    plt.xlim([-1200,4000])  
    plt.xlabel("Кол-во избирателей", size=16)    
    plt.ylabel("Частота", size=16)                
    plt.grid(True, alpha=0.3, linestyle="--")
    plt.show()

In [6]:
# Формируем Type DataFrame

type_path ="./CSV Samples/type_df.csv"
type_df = pd.read_csv(type_path)

type_df

,index,raw_voters,reg,tik,valid_ballots,invalid_ballots,population,population_group,Группа
0,70165,1001,Саратовская область,Балаковская,891,8,154813,6,1
1,46265,2068,Пермский край,"Пермь, Индустриальная",610,23,118008,5,1
2,19470,557,Кировская область,Белохолуницкая,296,6,14678,4,1
3,70855,437,Саратовская область,Калининская,376,3,62359,5,1
4,14369,582,Иркутская область,Иркутская - 94,358,6,56936,5,1
...,...,...,...,...,...,...,...,...,...
589,33684,906,Московская область,Коломенская городская № 2,284,27,27552,4,1
590,11429,510,Воронежская область,Павловская,429,0,205149,6,1
591,48059,1236,Приморский край,Дальнереченская городская,491,35,21820,4,1
592,29100,1066,Ленинградская область,Подпорожская,431,22,24144,4,1
593,20498,268,Кировская область,Унинская,169,6,6569,4,1

In [8]:
# Формируем Random DataFrame

random_path ="./CSV Samples/random_df.csv"
random_df = pd.read_csv(random_path)
random_df=random_df.drop('index',axis=1)

display(random_df)

,raw_voters,reg,tik,valid_ballots,invalid_ballots,population,population_group
0,1496,город Москва,район Чертаново Южное,496,12,67823,5
1,1672,Ленинградская область,Волховская,541,22,64120,5
2,1972,Чувашская Республика - Чувашия,"Чебоксары, Калининская",919,38,128769,5
3,2592,Краснодарский край,Динская,2364,16,108556,5
4,318,Республика Бурятия,Окинская,193,4,3861,3
...,...,...,...,...,...,...,...
589,801,Республика Саха (Якутия),Нерюнгринская,236,6,49279,4
590,1055,Самарская область,Жигулевская городская,373,11,45983,4
591,542,Оренбургская область,Матвеевская,332,0,9398,4
592,358,Чувашская Республика - Чувашия,Вурнарская,267,10,19681,4
593,925,Ставропольский край,Ипатовская,748,11,42871,4

In [10]:
# Формируем Mechanical DataFrame

mech_path ="./CSV Samples/mech_df.csv"
mech_df = pd.read_csv(mech_path)
mech_df=mech_df.drop('index',axis=1)

display(mech_df)

,raw_voters,reg,tik,valid_ballots,invalid_ballots,population,population_group
0,385,Алтайский край,Алтайская,174,4,37078,4
1,988,Алтайский край,Бийская,377,15,26480,4
2,1044,Алтайский край,Смоленская,432,11,19181,4
3,81,Алтайский край,Чарышская,37,0,9141,4
4,404,Алтайский край,Егорьевская,168,1,9937,4
...,...,...,...,...,...,...,...
590,2419,город Санкт-Петербург,Территориальная избирательная комиссия №21,911,8,113570,5
591,2987,город Санкт-Петербург,Территориальная избирательная комиссия №62,946,33,41072,4
592,2753,город Санкт-Петербург,Территориальная избирательная комиссия №27,831,17,90854,5
593,2540,город Санкт-Петербург,Территориальная избирательная комиссия №59,933,12,70213,5
594,1806,город Севастополь,Ленинская,685,16,245986,6

In [11]:
# Формируем отдельный DataFrame только с кол-вом избирателей для расчётов

mech_voters = mech_df['raw_voters']
print(mech_voters)

0       385
1       988
2      1044
3        81
4       404
       ...
590    2419
591    2987
592    2753
593    2540
594    1806
Name: raw_voters, Length: 595, dtype: int64

In [18]:
df = mech_df

col_list=['invalid_ballots', 'valid_ballots']
df['sum'] = df[col_list].sum(axis=1)
display(df)

,raw_voters,reg,tik,valid_ballots,invalid_ballots,population,population_group,sum
0,385,Алтайский край,Алтайская,174,4,37078,4,178
1,988,Алтайский край,Бийская,377,15,26480,4,392
2,1044,Алтайский край,Смоленская,432,11,19181,4,443
3,81,Алтайский край,Чарышская,37,0,9141,4,37
4,404,Алтайский край,Егорьевская,168,1,9937,4,169
...,...,...,...,...,...,...,...,...
590,2419,город Санкт-Петербург,Территориальная избирательная комиссия №21,911,8,113570,5,919
591,2987,город Санкт-Петербург,Территориальная избирательная комиссия №62,946,33,41072,4,979
592,2753,город Санкт-Петербург,Территориальная избирательная комиссия №27,831,17,90854,5,848
593,2540,город Санкт-Петербург,Территориальная избирательная комиссия №59,933,12,70213,5,945
594,1806,город Севастополь,Ленинская,685,16,245986,6,701

In [29]:
df['sum_city'] = df.groupby('reg', sort=True)["sum"].transform('sum')
display(df)

,raw_voters,reg,tik,valid_ballots,invalid_ballots,population,population_group,sum,sum_city,population_density,check
0,385,Алтайский край,Алтайская,174,4,37078,4,178,3529,0.05,1.02
1,988,Алтайский край,Бийская,377,15,26480,4,392,3529,0.11,1.02
2,1044,Алтайский край,Смоленская,432,11,19181,4,443,3529,0.13,1.02
3,81,Алтайский край,Чарышская,37,0,9141,4,37,3529,0.01,1.02
4,404,Алтайский край,Егорьевская,168,1,9937,4,169,3529,0.05,1.02
...,...,...,...,...,...,...,...,...,...,...,...
590,2419,город Санкт-Петербург,Территориальная избирательная комиссия №21,911,8,113570,5,919,8703,0.11,1.00
591,2987,город Санкт-Петербург,Территориальная избирательная комиссия №62,946,33,41072,4,979,8703,0.11,1.00
592,2753,город Санкт-Петербург,Территориальная избирательная комиссия №27,831,17,90854,5,848,8703,0.10,1.00
593,2540,город Санкт-Петербург,Территориальная избирательная комиссия №59,933,12,70213,5,945,8703,0.11,1.00
594,1806,город Севастополь,Ленинская,685,16,245986,6,701,701,1.00,1.00

In [30]:
# Формируем столбец "Плотность населения" по формуле: (Население населённого пункта / Сумму населения по региону) и округляем

df['population_density'] = (df['sum']/ df['sum_city']).round(2)
display(df)

,raw_voters,reg,tik,valid_ballots,invalid_ballots,population,population_group,sum,sum_city,population_density,check
0,385,Алтайский край,Алтайская,174,4,37078,4,178,3529,0.05,1.02
1,988,Алтайский край,Бийская,377,15,26480,4,392,3529,0.11,1.02
2,1044,Алтайский край,Смоленская,432,11,19181,4,443,3529,0.13,1.02
3,81,Алтайский край,Чарышская,37,0,9141,4,37,3529,0.01,1.02
4,404,Алтайский край,Егорьевская,168,1,9937,4,169,3529,0.05,1.02
...,...,...,...,...,...,...,...,...,...,...,...
590,2419,город Санкт-Петербург,Территориальная избирательная комиссия №21,911,8,113570,5,919,8703,0.11,1.00
591,2987,город Санкт-Петербург,Территориальная избирательная комиссия №62,946,33,41072,4,979,8703,0.11,1.00
592,2753,город Санкт-Петербург,Территориальная избирательная комиссия №27,831,17,90854,5,848,8703,0.10,1.00
593,2540,город Санкт-Петербург,Территориальная избирательная комиссия №59,933,12,70213,5,945,8703,0.11,1.00
594,1806,город Севастополь,Ленинская,685,16,245986,6,701,701,1.00,1.00

In [39]:
# Наблюдаем за отклонениями в рассчёте плотности населения, получаем удовлетворительные

df['check'] = df.groupby('reg', sort=False)["population_density"].transform('sum')
display(df)

,raw_voters,reg,tik,valid_ballots,invalid_ballots,population,population_group,sum,sum_city,population_density,check
0,385,Алтайский край,Алтайская,174,4,37078,4,178,3529,0.05,1.02
1,988,Алтайский край,Бийская,377,15,26480,4,392,3529,0.11,1.02
2,1044,Алтайский край,Смоленская,432,11,19181,4,443,3529,0.13,1.02
3,81,Алтайский край,Чарышская,37,0,9141,4,37,3529,0.01,1.02
4,404,Алтайский край,Егорьевская,168,1,9937,4,169,3529,0.05,1.02
...,...,...,...,...,...,...,...,...,...,...,...
590,2419,город Санкт-Петербург,Территориальная избирательная комиссия №21,911,8,113570,5,919,8703,0.11,1.00
591,2987,город Санкт-Петербург,Территориальная избирательная комиссия №62,946,33,41072,4,979,8703,0.11,1.00
592,2753,город Санкт-Петербург,Территориальная избирательная комиссия №27,831,17,90854,5,848,8703,0.10,1.00
593,2540,город Санкт-Петербург,Территориальная избирательная комиссия №59,933,12,70213,5,945,8703,0.11,1.00
594,1806,город Севастополь,Ленинская,685,16,245986,6,701,701,1.00,1.00

In [94]:
correlation_df=df[['population_group', 'population_density']]
correlation_df.to_csv('correlation_df.csv', index=False)

correlation_df=correlation_df.sort_values(by=['population_group'])
correlation_df=correlation_df.reset_index()
correlation_df=correlation_df.drop('index',axis=1)

display(correlation_df)

     population_group  population_density
0                   3                0.02
1                   3                0.04
2                   3                0.09
3                   3                0.16
4                   3                0.45
..                ...                 ...
590                 6                0.03
591                 6                0.03
592                 6                0.13
593                 6                0.07
594                 6                1.00

[595 rows x 2 columns]

In [113]:
# Самостоятельно рассчитываем коэффициент корреляции Спирмена

# Создаем столбец dx(порядок)
dx=[]
for i in range(len(correlation_df)):
    dx.append(i)
    

correlation_df['dx']=dx

# Создаем столбец dy, сортируя y 
dy=[]
y=correlation_df.population_density.tolist()
print('Столбец y:',y)
correlation_df['dy']=np.argsort(y)

# Рассчитываем столбец dd^2 (|dy-dx|^2)
correlation_df['dd2'] = (correlation_df['dx']-correlation_df['dy'])**2
display(correlation_df)

[0.02, 0.04, 0.09, 0.16, 0.45, 0.02, 0.02, 0.11, 0.01, 0.03, 0.02, 0.05, 0.04, 0.09, 0.12, 0.01, 0.06, 0.01, 0.01, 0.01, 0.06, 0.06, 0.94, 0.15, 0.46, 0.07, 0.09, 0.65, 0.13, 0.04, 0.16, 0.3, 0.06, 0.05, 0.23, 0.05, 0.11, 0.09, 0.03, 0.4, 0.13, 0.06, 1.0, 0.02, 0.02, 0.03, 0.06, 0.02, 0.0, 0.05, 0.05, 0.2, 0.12, 0.06, 0.12, 0.05, 0.13, 0.05, 0.06, 0.04, 0.08, 0.02, 0.04, 0.18, 0.05, 0.02, 0.09, 0.02, 0.23, 0.03, 0.35, 0.59, 0.06, 0.09, 0.05, 0.06, 0.01, 1.0, 0.47, 0.02, 0.08, 0.01, 0.01, 0.2, 0.01, 0.02, 0.15, 0.07, 0.05, 0.16, 0.09, 0.03, 0.06, 0.07, 0.0, 0.27, 0.24, 0.19, 0.03, 0.12, 0.14, 0.16, 0.07, 0.03, 0.01, 0.06, 0.36, 0.22, 0.05, 0.05, 0.08, 0.04, 0.04, 0.18, 0.24, 0.25, 0.08, 0.06, 0.13, 0.01, 0.12, 0.11, 0.09, 0.14, 0.17, 0.29, 0.14, 0.15, 0.13, 0.42, 0.07, 0.14, 0.11, 0.06, 0.11, 0.07, 0.02, 0.01, 0.02, 0.07, 0.06, 0.04, 0.1, 0.12, 0.4, 0.28, 0.27, 0.16, 0.04, 0.04, 0.3, 0.08, 0.04, 0.12, 0.03, 0.11, 0.54, 0.11, 0.05, 0.04, 0.03, 0.08, 0.08, 0.39, 0.05, 0.03, 0.02, 0.18, 0.11, 0.05, 0.03, 0.12, 0.03, 0.09, 0.01, 0.03, 0.07, 0.02, 0.03, 0.04, 0.07, 0.03, 0.05, 0.01, 0.06, 0.24, 0.12, 0.1, 0.01, 0.08, 0.14, 0.2, 0.07, 0.14, 0.49, 0.1, 0.13, 0.07, 0.02, 0.07, 0.07, 0.07, 0.07, 0.05, 0.04, 0.06, 0.03, 0.12, 0.19, 0.18, 0.33, 0.5, 0.27, 0.05, 0.02, 0.06, 0.09, 0.65, 0.35, 0.02, 0.03, 0.1, 0.07, 0.07, 0.03, 0.01, 0.02, 0.13, 0.12, 0.25, 0.26, 0.15, 0.14, 0.24, 0.97, 0.03, 0.49, 0.03, 0.06, 0.05, 0.73, 0.13, 0.14, 0.05, 0.11, 0.14, 0.17, 0.04, 0.13, 0.03, 0.13, 0.12, 0.01, 0.04, 0.01, 0.02, 0.51, 0.26, 0.07, 0.32, 0.06, 0.1, 0.11, 0.16, 0.11, 0.46, 0.08, 0.11, 0.13, 0.14, 0.16, 0.07, 0.02, 0.03, 0.19, 0.1, 0.05, 0.01, 0.13, 0.11, 0.21, 0.07, 0.05, 0.11, 0.03, 0.06, 0.0, 0.1, 0.18, 0.03, 0.19, 0.05, 0.04, 0.02, 0.05, 0.05, 0.07, 0.09, 0.14, 0.03, 0.02, 0.16, 0.21, 0.13, 0.07, 0.02, 0.01, 0.07, 0.06, 0.09, 0.07, 0.13, 0.04, 0.31, 0.32, 0.11, 0.11, 0.02, 0.07, 0.03, 0.04, 0.04, 0.16, 0.06, 0.09, 0.05, 0.11, 0.08, 0.25, 0.04, 0.01, 0.04, 0.04, 0.05, 0.17, 0.07, 0.04, 0.03, 0.13, 0.16, 0.08, 0.02, 0.04, 0.18, 0.18, 0.08, 0.21, 0.02, 0.09, 0.05, 0.2, 0.19, 0.09, 0.05, 0.29, 0.03, 0.03, 0.27, 0.09, 0.14, 0.04, 0.15, 0.09, 0.02, 0.15, 0.06, 0.24, 0.03, 0.11, 0.04, 0.01, 0.04, 0.09, 0.01, 0.18, 0.22, 0.03, 0.05, 0.22, 0.12, 0.21, 0.06, 0.04, 0.35, 0.55, 0.12, 0.1, 0.12, 0.09, 0.13, 0.09, 0.1, 0.36, 0.19, 0.01, 0.0, 0.05, 0.14, 0.08, 0.0, 0.05, 0.15, 0.06, 0.05, 0.01, 0.17, 0.09, 0.13, 0.03, 0.42, 0.02, 0.2, 0.01, 0.37, 0.02, 0.03, 0.06, 0.02, 0.19, 0.14, 0.11, 0.04, 0.25, 0.17, 0.11, 0.13, 0.17, 0.06, 0.1, 0.29, 0.25, 0.2, 0.14, 0.05, 0.14, 0.1, 0.15, 0.11, 0.02, 0.24, 0.08, 1.0, 0.11, 0.24, 0.88, 0.26, 0.26, 0.47, 0.08, 0.18, 0.38, 0.11, 0.15, 0.02, 0.11, 0.39, 0.24, 0.13, 0.29, 0.15, 0.26, 0.17, 0.08, 0.1, 0.15, 1.0, 0.1, 0.03, 0.03, 0.08, 0.07, 0.05, 0.06, 0.03, 0.02, 0.06, 0.06, 0.06, 0.06, 0.13, 0.03, 0.05, 0.06, 0.05, 0.03, 0.02, 0.14, 0.05, 0.07, 0.08, 0.09, 0.08, 0.11, 0.26, 0.08, 0.18, 0.07, 0.12, 0.02, 0.06, 0.22, 0.24, 0.07, 0.13, 0.05, 0.13, 0.13, 0.34, 0.29, 1.0, 0.29, 1.0, 0.09, 0.03, 0.37, 0.34, 0.42, 0.04, 0.17, 0.26, 0.6, 0.09, 0.38, 0.07, 0.14, 0.17, 0.04, 0.01, 0.06, 0.13, 0.2, 1.0, 0.71, 0.45, 0.05, 0.13, 0.06, 0.5, 0.08, 0.09, 0.06, 0.03, 0.04, 0.03, 0.06, 0.04, 0.05, 0.05, 0.04, 0.03, 0.1, 0.19, 0.12, 0.26, 0.12, 0.13, 0.12, 0.58, 0.21, 0.08, 0.18, 0.23, 0.1, 0.13, 0.32, 0.05, 0.17, 0.22, 0.06, 0.36, 0.38, 0.41, 0.22, 0.09, 0.11, 0.09, 0.07, 0.37, 0.17, 0.06, 0.13, 0.15, 0.15, 0.09, 0.07, 0.11, 0.11, 0.06, 0.41, 0.3, 0.03, 0.03, 0.13, 0.07, 1.0]

     population_group  population_density   dx   dy     dd2
0                   3                0.02    0  399  159201
1                   3                0.04    1  286   81225
2                   3                0.09    2   48    2116
3                   3                0.16    3   94    8281
4                   3                0.45    4  395  152881
..                ...                 ...  ...  ...     ...
590                 6                0.03  590  511    6241
591                 6                0.03  591   77  264196
592                 6                0.13  592  531    3721
593                 6                0.07  593  441   23104
594                 6                1.00  594  594       0

[595 rows x 5 columns]

In [114]:
# Рассчитываем сам коэффициент корреляции Спирмена

correlation =1-6*(correlation_df['dd2'].sum()/(len(correlation_df)**3-len(correlation_df)))
correlation

0.17377605506306648

In [115]:
correlation_df=correlation_df.drop([ 'dx','dy','dd2'],  axis=1)

In [116]:
# Рассчитываем то же самое, но со встроенным инструментом Pandas
correlation_df.corr ('spearman')

                    population_group  population_density
population_group            1.000000            0.167709
population_density          0.167709            1.000000

In [117]:
# Рассчитываем коэффициент корреляции Кендалла, но со встроенным инструментом Pandas
correlation_df.corr ('kendall')

                    population_group  population_density
population_group            1.000000            0.134026
population_density          0.134026            1.000000

In [118]:
# Рассчитываем коэффициент корреляции Кендалла, но со встроенным инструментом Pandas
correlation_df.corr ('pearson')

                    population_group  population_density
population_group            1.000000            0.103853
population_density          0.103853            1.000000